"""
Django settings for UtuberPickup project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ
from logging import getLogger

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# デバックモード設定
DEBUG = os.environ['DEBUG']

# logger設定

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[%(server_time)s] %(message)s a',
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'Utuberpickup.logger': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

logger = getLogger('Utuberpickup.logger')
logger.info('DEBUG : ' + DEBUG)

# 環境変数設定 ローカルではファイル読み込み
if DEBUG:
    env = environ.Env()
    ENV_FILE_DIR = environ.Path(__file__) - 3
    env_file = str(ENV_FILE_DIR.path('.env'))
    env.read_env(env_file)
    SECRET_KEY = env('SECRET_KEY')
    POSTGRES_DB = env('POSTGRES_DB')
    POSTGRES_USER = env('POSTGRES_USER')
    POSTGRES_PASSWORD = env('POSTGRES_PASSWORD')
    HOST_OS_DATABASE_PORT = env('HOST_OS_DATABASE_PORT')
    API_KEY1 = env('API_KEY1')
    API_KEY2 = env('API_KEY2')
    API_KEY3 = env('API_KEY3')
    API_KEY4 = env('API_KEY4')
    API_KEY5 = env('API_KEY5')
else:
    SECRET_KEY = os.environ['SECRET_KEY']
    POSTGRES_DB = os.environ['POSTGRES_DB']
    POSTGRES_USER = os.environ['POSTGRES_USER']
    POSTGRES_PASSWORD = os.environ['POSTGRES_PASSWORD']
    HOST_OS_DATABASE_PORT = os.environ['HOST_OS_DATABASE_PORT']
    API_KEY1 = os.environ['API_KEY1']
    API_KEY2 = os.environ['API_KEY2']
    API_KEY3 = os.environ['API_KEY3']
    API_KEY4 = os.environ['API_KEY4']
    API_KEY5 = os.environ['API_KEY5']

ALLOWED_HOSTS = ['localhost',
                 '0.0.0.0',
                 '127.0.0.1',
                 'ec2-54-248-23-107.ap-northeast-1.compute.amazonaws.com',
                 'vtuber-livechat-analytics.tk'
                 ]

INSTALLED_APPS = [
    'apps.myrestapi.apps.MyrestapiConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': 'db',
        'PORT': HOST_OS_DATABASE_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = (
#     [
#         os.path.join(BASE_DIR, 'static')
#     ]
# )

#INTERNAL_IPS = [
    #'127.0.0.1',
#    '0.0.0.0'
#]

# if DEBUG:
#     def show_toolbar(request):
#         return True
#
#     INSTALLED_APPS += (
#         'debug_toolbar',
#     )
#     MIDDLEWARE += (
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     )
#     # ここで表示する内容を設定できます↓↓基本的にはこれでok
#     DEBUG_TOOLBAR_CONFIG = {
#         'SHOW_TOOLBAR_CALLBACK': show_toolbar,
#     }