version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432" 
  web:
    build:
      context: ./
      dockerfile: ./UtuberPickup/Dockerfile
    volumes:
      - ./UtuberPickup/cron.d/crontab:/var/spool/cron/crontabs/root
      - ./UtuberPickup/cron.d/regularGetYoutubeComments.sh:/var/spool/cron/crontabs/regularGetYoutubeComments.sh
    env_file:
      - ./.env
    environment:
        DEBUG: ${DEBUG}
    command: gunicorn UtuberPickup.config.wsgi:application --bind=0.0.0.0:80 --workers 2 --threads 2
    expose:
      - 80
    depends_on:
      - db

  nginx:
      build: ./${NGINX_ENV}
      env_file:
        - ./.env
      volumes:
        - ./${NGINX_ENV}/nginx.conf:/etc/nginx/nginx.conf
        - ./UtuberPickup/static:/static
      ports:
          - '8080:80'
      depends_on:
          - web

#  busybox:
#    build: ./UtuberPickup/cron.d/
#    volumes:
#      - ./UtuberPickup/cron.d/crontab:/var/spool/cron/crontabs/root
#    depends_on:
#      - web

# volumes を定義する
volumes:
  # volume の名前を指定
  db-data:
    # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    external: true