version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/code
    ports:
      - "5432:5432" 
  web:
    build:
      context: ./
      dockerfile: ./UtuberPickup/Dockerfile
    command: gunicorn UtuberPickup.config.wsgi:application --bind=0.0.0.0:8000 --workers 2 --threads 2
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db

  nginx:
      build: ./nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - '8000:8000'
      depends_on:
          - web