# Generated by Django 3.0.6 on 2020-10-27 15:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCacheModel',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('time_list', jsonfield.fields.JSONField()),
                ('moderator_chat_list', jsonfield.fields.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_Vtuber_InformationModel',
            fields=[
                ('channel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('vtuber_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
